--테이블 생성
--CREATE TABLE 테이블명 (
--  열명 자로형(길이) (기본값 OR 제약조건)
--);

/*

    14-2 NOT NULL
    
*/
 

--실습 14-1 테이블을 생성할 때 NOT NULL 설정하기

CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_NOTNULL;

--실습 14-2 제약조건이 NOT NULL인 열에 NULL 넣어 보기

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', NULL, '010-1234-5678');
    
--실습 14-3 제약조건이 없는 TEL 열에 NULL 입력하기

INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD) 
    VALUES ('TEST_ID_01', '1234');
    
SELECT * FROM TABLE_NOTNULL;

--실습 14-4 NOT NULL 제약 조건이 지정된 열 데이터를 NULL로 업데이트하기

UPDATE TABLE_NOTNULL
    SET LOGIN_PWD = NULL
    WHERE LOGIN_ID = 'TEST_ID_01';
    
--실습 14-5 제약 조건 살펴보기(SCOTT 계정)

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
--실습 14-6 테이블을 생성할 때 제약 조건에 이름 지정하기
--제약 조건 유지보수(삭제...) 할때  쉽게 하기 위해서 이름을 지정

CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
--실습 14-7 TEL 열에 NOT NULL 제약 조건 추가하기

ALTER TABLE TABLE_NOTNULL
    MODIFY(TEL NOT NULL);
    
--실습 14-8 TEL 열 데이터 수정하기
    
UPDATE TABLE_NOTNULL
    SET TEL = '010-1234-5678'
    WHERE LOGIN_ID = 'TEST_ID_01';
    
SELECT * FROM TABLE_NOTNULL;

--실습 14-9 NOT NULL 제약 조건 추가하기

ALTER TABLE TABLE_NOTNULL
    MODIFY(TEL NOT NULL);
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
--실습 14-10 제약 조건에 이름 지정해서 추가하기

ALTER TABLE TABLE_NOTNULL2
    MODIFY(TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
--실습 14-11 TABLE_NOTNULL2 테이블 열 구조 확인하기

DESC TABLE_NOTNULL2;

--실습 14-12 이미 생성한 제약 조건 이름 변경하기

ALTER TABLE TABLE_NOTNULL2
    RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
--실습 14-13 제약 조건 삭제하기

ALTER TABLE TABLE_NOTNULL2
    DROP CONSTRAINT TBLNN2_TEL_NN;

DESC TABLE_NOTNULL2;


/*

    14-2 UNIQUE
    
*/


--실습 14-14 제약 조건 지정하기(테이블을 생성할 때)

CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR(20) UNIQUE,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_UNIQUE;

--실습 14-15 USER_CONSTRAINTS 데이터 사전 뷰로 제약 조건 확인하기

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TABLE_UNIQUE';
    
--실습 14-16 TABLE_UNIQUE 테이블에 데이터 입력하기

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678');
    
SELECT * FROM TABLE_UNIQUE;

--실습 14-17 LOGIN_ID 열에 중복되는 데이터 넣기

INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
    VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678');
    
--실습 14-18 TABLE_UNIQUE 테이블에 데이터 입력하기

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_02', 'PWD01', '010-1234-5678');
    
SELECT * FROM TABLE_UNIQUE;

--실습 14-19 UNIQUE 제약 조건을 지정한 열에 NULL 입력하기

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL) 
    VALUES (NULL, 'PWD01', '010-2345-6789');
    
SELECT * FROM TABLE_UNIQUE;

--실습 14-20 TABLE_UNIQUE 테이블 데이터 수정하기

UPDATE TABLE_UNIQUE
    SET LOGIN_ID = 'TEST_ID_01'
    WHERE LOGIN_ID IS NULL;
    
--실습 14-21 테이블을 생성할 때 UNIQUE 제약 조건 설정하기

CREATE TABLE TABLE_UNIQUE2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);

--실습 14-22 생성한 UNIQUE 제약 조건 확인하기(USER_CONSTRAINTS 사용)

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
--실습 14-23 이미 생성한 테이블 열에 UNIQUE 제약 조건 추가하기

ALTER TABLE TABLE_UNIQUE
    MODIFY(TEL UNIQUE);
    
--실습 14-24 TEL 열을 모두 NULL로 변경하기

UPDATE TABLE_UNIQUE
    SET TEL = NULL;
    
SELECT * FROM TABLE_UNIQUE;

--실습 14-25 TEL 값에 UNIQUE 제약 조건 설정하기

ALTER TABLE TABLE_UNIQUE
    MODIFY(TEL UNIQUE);
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
--실습 14-26 UNIQUE 제약 조건 이름 직접 지정하기

ALTER TABLE TABLE_UNIQUE2
    MODIFY(TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE);
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
--실습 14-27 이미 있는 UNIQUE 제약 조건 이름 수정하기

ALTER TABLE TABLE_UNIQUE2
    RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
--실습 14-28 제약 조건 삭제하기

ALTER TABLE TABLE_UNIQUE2
    DROP CONSTRAINT TBLUNQ2_TEL_UNQ;
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';
    
    
/*

    14-3    PRIMARY KEY
    
*/
    
    
--실습 14-29 테이블을 생성할 때 특정 열에 PRIMARY KEY 설정하기

CREATE TABLE TABLE_PK(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_PK;

--실습 14-30 생성한 PRIMARY KEY 확인하기

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_PK%';
    
--실습 14-31 생성한 PRIMARY KEY로 자동 생성된 INDEX 확인하기

SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
    FROM USER_INDEXES
    WHERE TABLE_NAME LIKE 'TABLE_PK%';
    
--실습 14-32 제약 조건의 이름을 직접 지정하여 테이블 생성하기

CREATE TABLE TABLE_PK2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPD_NN NOT NULL,
    TEL VARCHAR2(20)
);

--실습 14-33 TABLE_PK 테이블에 데이터 입력하기

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES('TEST_ID_01', 'PWD01', '010-1234-5678');
    
SELECT * FROM TABLE_PK;

--실습 14-34 TABLE_PK 테이블에 중복 데이터 입력하기

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES ('TEST_ID_01', 'PWD02', '010-2345-6789');
    
--실습 14-35 NULL 을 명시적으로 입력하기

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
    VALUES (NULL, 'PWD02', '010-2345-6789');
    
--실습 14-36 NULL을 암시적으로 입력하기

INSERT INTO TABLE_PK(LOGIN_PWD, TEL)
    VALUES ('PWD02', '010-2345-6789');
    
--CREATE 문에서 제약 조건을 지정하는 다른 방식

CREATE TABLE TABLE_NAME(
    COL1 VARCHAR2(20),
    COL2 VARCHAR2(20),
    COL3 VARCHAR2(20),
    PRIMARY KEY (COL1),
    CONSTRAINT CONSTRAINT_NAME UNIQUE (COL2)
)



    
/*

    14-4    FOREIGN KEY
    
*/

    
    
--실습 14-37 EMP 테이블과 DEPT 테이블의 제약 조건 살펴보기

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN ('EMP', 'DEPT');
    
--실습 14-38 FOREIGN KEY가 참조하는 열에 없는 데이터 입력하기

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(9999, '홍길동', 'CLERK', '7788', TO_DATE('2017/04/30', 'YYYY/MM/DD'), 1200, NULL, 50);
    
--실습 14-39 DEPT_FK 테이블 생성하기

CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

DESC DEPT_FK;

--실습 14-40 EMP_FK 테이블 생성하기

CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DESC EMP_FK;

--실습 14-41 EMP_FK 테이블에 데이터 삽입하기(DEPTNO 데이터가 아직 DEPT_FK 테이블에 없을 때)

INSERT INTO EMP_FK
    VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'), 3000, NULL, 10);
    
--실습 14-42 DEPT_FK에 데이터 삽입하기

INSERT INTO DEPT_FK
    VALUES(10, 'TEST_DNAME', 'TEST_LOC');
    
SELECT * FROM DEPT_FK;

--실습 14-43 EMP_FK 테이블에 데이터 삽입하기

INSERT INTO EMP_FK
    VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'), 3000, NULL, 10);
    
SELECT * FROM EMP_FK;

--실습 14-44 DEPT_FK 테이블의 10번 부서 데이터 삭제하기

DELETE FROM DEPT_FK
    WHERE DEPTNO = 10;
    


    
/*

    14-5    CHECK
    
*/



--실습 14-45 테이블을 생성할 때 CHECK 제약 조건 설정하기

CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK( LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2(20)
);

DESC TABLE_CHECK;

--실습 14-46 CHECK 제약 조건에 맞지 않는 예

INSERT INTO TABLE_CHECK
    VALUES ('TEST_ID_01', '123', '010-1234-5678');
    
--실습 14-47 CHECK 제약 조건에 맞는 예

INSERT INTO TABLE_CHECK
    VALUES ('TEST_ID_01', '1234', '010-1234-5678');
    
SELECT * FROM TABLE_CHECK;

--실습 14-48 CHECK 제약 조건 확인하기

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_CHECK';
    


    
/*

    14-6    DEFAULT
    
*/



--실습 14-49 테이블을 생성할 때 DEFAULT 제약 조건 설정하기

CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20)
);

DESC TABLE_DEFAULT;

--실습 14-50 DEFAULT로 지정한 기본값을 입력하는 INSERT문 확인하기

INSERT INTO TABLE_DEFAULT
    VALUES ('TEST_ID', NULL, '010-1234-5678');
    
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) 
    VALUES ('TEST_ID2', '010-1234-5678');
    
SELECT * FROM TABLE_DEFAULT;

--제약조건 비활성화, 활성화

--ALTER TABLE TABLE_NAME
--    DISABLE [NOVALIDATE / VALIDATE(선택)] CONSTRAINT CONSTRAINT_NAME;
--    
--ALTER TABLE TABLE_NAME
--    ENABLE [NOVALIDATE / VALIDATE(선택)] CONSTRAINT CONSTRAINT_NAME;





-- 실습 한 테이블 정리
/*

DROP TABLE TABLE_NOTNULL;
DROP TABLE TABLE_NOTNULL2;
DROP TABLE TABLE_UNIQUE;
DROP TABLE TABLE_UNIQUE2;
DROP TABLE TABLE_PK;
DROP TABLE TABLE_PK2;
DROP TABLE EMP_FK;
DROP TABLE DEPT_FK;
DROP TABLE TABLE_CHECK;
DROP TABLE TABLE_DEFAULT;

*/

